name: links

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --accept '200..=299,403,429' README.md
